-- Generated by HyprMod

-- Settings
hl.config({
    cursor = {
        no_hardware_cursors = 0,
    },
    dwindle = {
        default_split_ratio = 0.8,
        smart_split = true,
    },
    ecosystem = {
        no_update_news = false,
    },
    misc = {
        animate_manual_resizes = true,
        animate_mouse_windowdragging = true,
    },
})

-- Animations
hl.animation({
    leaf = "borderangle",
    enabled = false,
})

-- Monitors
hl.monitor({
    output = "DP-1",
    disabled = false,
    mode = "2560x1440@164.96Hz",
    position = "0x0",
    scale = 1,
    transform = 1,
    bitdepth = 10,
    cm = "wide",
})
hl.monitor({
    output = "DP-2",
    disabled = false,
    mode = "3440x1440@240.09Hz",
    position = "1440x540",
    scale = 1,
    bitdepth = 10,
    cm = "wide",
    sdrbrightness = 0.5,
    sdr_min_luminance = 0,
    sdr_max_luminance = 604,
    min_luminance = 0,
    max_luminance = 604,
    max_avg_luminance = 277,
})
hl.monitor({
    output = "HDMI-A-1",
    disabled = true,
})

-- Keybinds
hl.unbind("SUPER + B")
hl.bind("SUPER + B", hl.dsp.exec_cmd("uwsm app -- app.zen_browser.zen"))
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.exec_cmd("noctalia msg panel-toggle wallpaper"))
hl.unbind("SUPER + SHIFT + W")
hl.bind("SUPER + SHIFT + W", hl.dsp.exec_cmd("noctalia msg panel-toggle noctalia/wallhaven:browser"))
