color0 #21302f
color1 #fd4663
color2 #8bc1bd
color3 #d3dfe9
color4 #8285b0
color5 #acd3d0
color6 #aac1d5
color7 #f2f3f3
color8 #5e6e6d
color9 #fd4663
color10 #8bc1bd
color11 #d3dfe9
color12 #8285b0
color13 #acd3d0
color14 #aac1d5
color15 #f2f3f3

cursor                #f2f3f3
cursor_text_color     #000000
background            #000000
foreground            #f2f3f3
selection_foreground  #afb6b6
selection_background  #21302f
active_border_color   #8bc1bd
inactive_border_color #061514
url_color             #8bc1bd

active_tab_foreground   #1b2222
active_tab_background   #8bc1bd
inactive_tab_foreground #afb6b6
inactive_tab_background #061514
cursor_trail_color      #afb6b6
