color0 #484459
color1 #ffb4ab
color2 #8dcdff
color3 #96cdf8
color4 #c8bfff
color5 #8dcdff
color6 #96cdf8
color7 #e5e0ef
color8 #928ea5
color9 #ffb4ab
color10 #8dcdff
color11 #96cdf8
color12 #c8bfff
color13 #8dcdff
color14 #96cdf8
color15 #e5e0ef

cursor                #e5e0ef
cursor_text_color     #000000
background            #000000
foreground            #e5e0ef
selection_foreground  #c9c3dc
selection_background  #484459
active_border_color   #8dcdff
inactive_border_color #3a364b
url_color             #8dcdff

active_tab_foreground   #00344f
active_tab_background   #8dcdff
inactive_tab_foreground #c9c3dc
inactive_tab_background #3a364b
cursor_trail_color      #c9c3dc
